disabled_rules:
  - static_over_final_class
  - non_optional_string_data_conversion
  - trailing_whitespace
  - line_length
  - vertical_whitespace
  - unused_closure_parameter
  - comment_spacing
  - trailing_newline
  - identifier_name
  - colon
  - mark
  - todo
  - cyclomatic_complexity
