name: Pull Request Slack Bot

on:
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on PR
        if: github.event.review.state == 'APPROVED'
        uses: 8398a7/action-slack@v3
        with:
          status: 'good'
          title: 'Pull Request Approved'
          text: '코드 리뷰가 성공적으로 승인되었습니다.'
          fields: repo,actor,base_ref,head_ref
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on PR
        if: github.event.review.state == 'changes_requested' 
        uses: 8398a7/action-slack@v3
        with:
          status: 'danger'
          title: 'Changes Requested in Pull Request'
          text: '코드 수정이 필요합니다. 확인해 주세요.'
          fields: repo,actor,base_ref,head_ref
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          
      - name: Notify Slack on PR
        if: github.event.action == 'pull_request_review_comment' 
        uses: 8398a7/action-slack@v3
        with:
          status: 'good'
          title: 'review comment'
          text: '리뷰 comment가 추가되었습니다.'
          fields: repo,actor,base_ref,head_ref
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

          
